import type {
  Patient,
  Doctor,
  Nurse,
  Appointment,
  Bed,
  Medicine,
  LabTest,
  RadiologyScan,
  Invoice,
  AuditLog,
  Notification,
  SoapNote,
} from './types';

export const currentUser = {
  id: 'u001',
  name: 'Dr. Aarav Sharma',
  email: 'aarav.sharma@medset.in',
  role: 'doctor' as const,
  phone: '+91 98765 43210',
  department: 'Cardiology',
  avatar: '',
};

export const patients: Patient[] = [
  {
    id: 'p001',
    mrn: 'MEDSET-2026-0001',
    name: 'Rajesh Kumar',
    age: 54,
    gender: 'Male',
    phone: '+91 98111 22334',
    bloodGroup: 'B+',
    address: '12 MG Road, Bengaluru, KA 560001',
    status: 'ICU',
    ward: 'ICU-1',
    bed: 'ICU-Bed-04',
    admissionDate: '2026-08-04',
    diagnosis: 'Acute Myocardial Infarction',
    doctor: 'Dr. Aarav Sharma',
    insurance: 'Star Health',
    vitals: {
      heartRate: 92,
      bloodPressure: '140/90',
      temperature: 99.2,
      oxygenSaturation: 94,
      respiratoryRate: 20,
      recordedAt: '2026-08-06T08:30:00',
    },
    allergies: ['Penicillin', 'Sulfa drugs'],
    medications: ['Aspirin 75mg', 'Atorvastatin 40mg', 'Metoprolol 25mg'],
    history: [
      { id: 'h1', date: '2026-08-04', type: 'Admission', title: 'ER Admission', description: 'Chest pain, admitted to ICU', doctor: 'Dr. Aarav Sharma' },
      { id: 'h2', date: '2026-08-04', type: 'Lab', title: 'Troponin I', description: 'Elevated troponin levels (4.2 ng/mL)', doctor: 'Dr. Aarav Sharma' },
      { id: 'h3', date: '2026-08-05', type: 'Radiology', title: 'Echocardiogram', description: 'LVEF 42%, mild LV dysfunction' },
    ],
  },
  {
    id: 'p002',
    mrn: 'MEDSET-2026-0002',
    name: 'Priya Nair',
    age: 31,
    gender: 'Female',
    phone: '+91 98222 33445',
    bloodGroup: 'O+',
    address: '45 Marine Drive, Mumbai, MH 400020',
    status: 'Admitted',
    ward: 'General Ward B',
    bed: 'GW-B-12',
    admissionDate: '2026-08-05',
    diagnosis: 'Pyelonephritis',
    doctor: 'Dr. Meera Iyer',
    insurance: 'HDFC Ergo',
    vitals: {
      heartRate: 88,
      bloodPressure: '118/76',
      temperature: 101.4,
      oxygenSaturation: 98,
      respiratoryRate: 18,
      recordedAt: '2026-08-06T07:45:00',
    },
    allergies: [],
    medications: ['Ceftriaxone 1g IV', 'Paracetamol 650mg'],
    history: [
      { id: 'h1', date: '2026-08-05', type: 'Admission', title: 'Admission', description: 'Fever and flank pain', doctor: 'Dr. Meera Iyer' },
    ],
  },
  {
    id: 'p003',
    mrn: 'MEDSET-2026-0003',
    name: 'Mohammed Ali',
    age: 67,
    gender: 'Male',
    phone: '+91 98333 44556',
    bloodGroup: 'A+',
    address: '23 Charminar Road, Hyderabad, TS 500002',
    status: 'Outpatient',
    diagnosis: 'Type 2 Diabetes Mellitus',
    doctor: 'Dr. Vikram Reddy',
    vitals: {
      heartRate: 76,
      bloodPressure: '128/82',
      temperature: 98.4,
      oxygenSaturation: 97,
      respiratoryRate: 16,
      recordedAt: '2026-08-06T09:00:00',
    },
    allergies: ['Metformin'],
    medications: ['Glimepiride 2mg', 'Pioglitazone 15mg'],
    history: [
      { id: 'h1', date: '2026-08-06', type: 'Visit', title: 'OPD Follow-up', description: 'HbA1c 7.8%, adjusted medication', doctor: 'Dr. Vikram Reddy' },
    ],
  },
  {
    id: 'p004',
    mrn: 'MEDSET-2026-0004',
    name: 'Ananya Desai',
    age: 28,
    gender: 'Female',
    phone: '+91 98444 55667',
    bloodGroup: 'AB+',
    address: '67 Law Garden, Ahmedabad, GJ 380006',
    status: 'Emergency',
    diagnosis: 'Acute Appendicitis',
    doctor: 'Dr. Suresh Patel',
    vitals: {
      heartRate: 104,
      bloodPressure: '110/70',
      temperature: 100.8,
      oxygenSaturation: 96,
      respiratoryRate: 22,
      recordedAt: '2026-08-06T06:15:00',
    },
    allergies: [],
    medications: [],
    history: [
      { id: 'h1', date: '2026-08-06', type: 'Admission', title: 'ER Admission', description: 'Right lower quadrant pain, scheduled for appendectomy' },
    ],
  },
  {
    id: 'p005',
    mrn: 'MEDSET-2026-0005',
    name: 'Lakshmi Krishnan',
    age: 45,
    gender: 'Female',
    phone: '+91 98555 66778',
    bloodGroup: 'O-',
    address: '89 Anna Salai, Chennai, TN 600002',
    status: 'Discharged',
    diagnosis: 'Hypertension',
    doctor: 'Dr. Aarav Sharma',
    vitals: {
      heartRate: 72,
      bloodPressure: '125/80',
      temperature: 98.6,
      oxygenSaturation: 99,
      respiratoryRate: 16,
      recordedAt: '2026-08-01T10:00:00',
    },
    allergies: ['Aspirin'],
    medications: ['Amlodipine 5mg'],
    history: [
      { id: 'h1', date: '2026-07-28', type: 'Admission', title: 'Admission', description: 'Hypertensive urgency', doctor: 'Dr. Aarav Sharma' },
      { id: 'h2', date: '2026-08-01', type: 'Discharge', title: 'Discharge', description: 'BP stabilized, discharged with medications' },
    ],
  },
  {
    id: 'p006',
    mrn: 'MEDSET-2026-0006',
    name: 'Arjun Singh',
    age: 38,
    gender: 'Male',
    phone: '+91 98666 77889',
    bloodGroup: 'B-',
    address: '34 Park Street, Kolkata, WB 700016',
    status: 'Admitted',
    ward: 'General Ward A',
    bed: 'GW-A-07',
    admissionDate: '2026-08-03',
    diagnosis: 'Pneumonia',
    doctor: 'Dr. Meera Iyer',
    insurance: 'ICICI Lombard',
    vitals: {
      heartRate: 95,
      bloodPressure: '130/85',
      temperature: 100.2,
      oxygenSaturation: 91,
      respiratoryRate: 24,
      recordedAt: '2026-08-06T08:00:00',
    },
    allergies: [],
    medications: ['Azithromycin 500mg', 'Oxygen 2L/min'],
    history: [
      { id: 'h1', date: '2026-08-03', type: 'Admission', title: 'Admission', description: 'Productive cough, fever, hypoxia', doctor: 'Dr. Meera Iyer' },
    ],
  },
];

export const doctors: Doctor[] = [
  { id: 'd001', name: 'Dr. Aarav Sharma', specialization: 'Cardiologist', department: 'Cardiology', phone: '+91 98765 43210', email: 'aarav.sharma@medset.in', experience: 15, status: 'Available', patientsToday: 8, rating: 4.9, qualifications: ['MBBS', 'MD (Medicine)', 'DM (Cardiology)'] },
  { id: 'd002', name: 'Dr. Meera Iyer', specialization: 'Pulmonologist', department: 'Pulmonology', phone: '+91 98765 43211', email: 'meera.iyer@medset.in', experience: 12, status: 'Busy', patientsToday: 6, rating: 4.8, qualifications: ['MBBS', 'MD (Pulmonary Medicine)'] },
  { id: 'd003', name: 'Dr. Vikram Reddy', specialization: 'Endocrinologist', department: 'Endocrinology', phone: '+91 98765 43212', email: 'vikram.reddy@medset.in', experience: 10, status: 'Available', patientsToday: 5, rating: 4.7, qualifications: ['MBBS', 'MD (Medicine)', 'DM (Endocrinology)'] },
  { id: 'd004', name: 'Dr. Suresh Patel', specialization: 'General Surgeon', department: 'Surgery', phone: '+91 98765 43213', email: 'suresh.patel@medset.in', experience: 18, status: 'Busy', patientsToday: 4, rating: 4.9, qualifications: ['MBBS', 'MS (General Surgery)'] },
  { id: 'd005', name: 'Dr. Kavya Menon', specialization: 'Neurologist', department: 'Neurology', phone: '+91 98765 43214', email: 'kavya.menon@medset.in', experience: 14, status: 'On Leave', patientsToday: 0, rating: 4.8, qualifications: ['MBBS', 'MD (Medicine)', 'DM (Neurology)'] },
  { id: 'd006', name: 'Dr. Rohit Gupta', specialization: 'Orthopedic Surgeon', department: 'Orthopedics', phone: '+91 98765 43215', email: 'rohit.gupta@medset.in', experience: 11, status: 'Available', patientsToday: 7, rating: 4.6, qualifications: ['MBBS', 'MS (Orthopedics)'] },
  { id: 'd007', name: 'Dr. Sneha Joshi', specialization: 'Pediatrician', department: 'Pediatrics', phone: '+91 98765 43216', email: 'sneha.joshi@medset.in', experience: 9, status: 'Available', patientsToday: 10, rating: 4.9, qualifications: ['MBBS', 'MD (Pediatrics)'] },
  { id: 'd008', name: 'Dr. Arjun Nair', specialization: 'Nephrologist', department: 'Nephrology', phone: '+91 98765 43217', email: 'arjun.nair@medset.in', experience: 16, status: 'Off Duty', patientsToday: 0, rating: 4.7, qualifications: ['MBBS', 'MD (Medicine)', 'DM (Nephrology)'] },
];

export const nurses: Nurse[] = [
  { id: 'n001', name: 'Sunita Williams', department: 'ICU', shift: 'Morning', status: 'On Duty', assignedWard: 'ICU-1', phone: '+91 97000 11111', experience: 8 },
  { id: 'n002', name: 'Ramesh Chauhan', department: 'ICU', shift: 'Night', status: 'On Duty', assignedWard: 'ICU-1', phone: '+91 97000 22222', experience: 6 },
  { id: 'n003', name: 'Fatima Begum', department: 'General', shift: 'Morning', status: 'On Duty', assignedWard: 'General Ward A', phone: '+91 97000 33333', experience: 5 },
  { id: 'n004', name: 'Deepika Rao', department: 'Emergency', shift: 'Evening', status: 'Break', assignedWard: 'ER', phone: '+91 97000 44444', experience: 7 },
  { id: 'n005', name: 'Joseph Thomas', department: 'ICU', shift: 'Evening', status: 'Off Duty', assignedWard: 'ICU-2', phone: '+91 97000 55555', experience: 10 },
  { id: 'n006', name: 'Anita Verma', department: 'General', shift: 'Morning', status: 'On Duty', assignedWard: 'General Ward B', phone: '+91 97000 66666', experience: 4 },
];

export const appointments: Appointment[] = [
  { id: 'a001', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', doctorName: 'Dr. Aarav Sharma', department: 'Cardiology', date: '2026-08-06', time: '09:00', duration: 30, type: 'Consultation', status: 'In Progress', reason: 'Post-MI follow-up' },
  { id: 'a002', patientName: 'Mohammed Ali', patientMrn: 'MEDSET-2026-0003', doctorName: 'Dr. Vikram Reddy', department: 'Endocrinology', date: '2026-08-06', time: '09:30', duration: 20, type: 'Follow-up', status: 'Checked-in', reason: 'Diabetes management review' },
  { id: 'a003', patientName: 'Sneha Pillai', patientMrn: 'MEDSET-2026-0007', doctorName: 'Dr. Sneha Joshi', department: 'Pediatrics', date: '2026-08-06', time: '10:00', duration: 15, type: 'Check-up', status: 'Scheduled', reason: 'Routine vaccination' },
  { id: 'a004', patientName: 'Ananya Desai', patientMrn: 'MEDSET-2026-0004', doctorName: 'Dr. Suresh Patel', department: 'Surgery', date: '2026-08-06', time: '10:30', duration: 45, type: 'Emergency', status: 'In Progress', reason: 'Appendectomy consultation' },
  { id: 'a005', patientName: 'Vikas Malhotra', patientMrn: 'MEDSET-2026-0008', doctorName: 'Dr. Rohit Gupta', department: 'Orthopedics', date: '2026-08-06', time: '11:00', duration: 30, type: 'Consultation', status: 'Scheduled', reason: 'Knee pain evaluation' },
  { id: 'a006', patientName: 'Lakshmi Krishnan', patientMrn: 'MEDSET-2026-0005', doctorName: 'Dr. Aarav Sharma', department: 'Cardiology', date: '2026-08-06', time: '11:30', duration: 20, type: 'Follow-up', status: 'Completed', reason: 'BP medication review' },
  { id: 'a007', patientName: 'Arjun Singh', patientMrn: 'MEDSET-2026-0006', doctorName: 'Dr. Meera Iyer', department: 'Pulmonology', date: '2026-08-06', time: '12:00', duration: 30, type: 'Consultation', status: 'Checked-in', reason: 'Pneumonia review' },
  { id: 'a008', patientName: 'Kavya Reddy', patientMrn: 'MEDSET-2026-0009', doctorName: 'Dr. Vikram Reddy', department: 'Endocrinology', date: '2026-08-06', time: '14:00', duration: 20, type: 'Follow-up', status: 'Scheduled', reason: 'Thyroid panel review' },
  { id: 'a009', patientName: 'Rahul Mehta', patientMrn: 'MEDSET-2026-0010', doctorName: 'Dr. Rohit Gupta', department: 'Orthopedics', date: '2026-08-06', time: '14:30', duration: 30, type: 'Consultation', status: 'Scheduled', reason: 'Fracture follow-up' },
  { id: 'a010', patientName: 'Priya Nair', patientMrn: 'MEDSET-2026-0002', doctorName: 'Dr. Meera Iyer', department: 'Pulmonology', date: '2026-08-06', time: '15:00', duration: 20, type: 'Follow-up', status: 'Scheduled', reason: 'Pyelonephritis review' },
];

export const beds: Bed[] = [
  { id: 'b001', number: 'ICU-Bed-01', ward: 'ICU-1', type: 'ICU-Ventilator', status: 'Occupied', patientName: 'Suresh Yadav', patientMrn: 'MEDSET-2026-0011', assignedDoctor: 'Dr. Aarav Sharma', assignedNurse: 'Sunita Williams', ventilator: true, monitor: true, admittedAt: '2026-08-02', estimatedDischarge: '2026-08-10' },
  { id: 'b002', number: 'ICU-Bed-02', ward: 'ICU-1', type: 'ICU', status: 'Available', ventilator: false, monitor: true },
  { id: 'b003', number: 'ICU-Bed-03', ward: 'ICU-1', type: 'ICU-Ventilator', status: 'Occupied', patientName: 'Geeta Rao', patientMrn: 'MEDSET-2026-0012', assignedDoctor: 'Dr. Kavya Menon', assignedNurse: 'Ramesh Chauhan', ventilator: true, monitor: true, admittedAt: '2026-08-04', estimatedDischarge: '2026-08-12' },
  { id: 'b004', number: 'ICU-Bed-04', ward: 'ICU-1', type: 'ICU-Ventilator', status: 'Occupied', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', assignedDoctor: 'Dr. Aarav Sharma', assignedNurse: 'Sunita Williams', ventilator: true, monitor: true, admittedAt: '2026-08-04', estimatedDischarge: '2026-08-09' },
  { id: 'b005', number: 'ICU-Bed-05', ward: 'ICU-1', type: 'ICU', status: 'Maintenance', ventilator: false, monitor: true },
  { id: 'b006', number: 'ICU-Bed-06', ward: 'ICU-1', type: 'ICU', status: 'Available', ventilator: false, monitor: true },
  { id: 'b007', number: 'ICU-Bed-07', ward: 'ICU-2', type: 'ICU-Ventilator', status: 'Occupied', patientName: 'Manoj Tiwari', patientMrn: 'MEDSET-2026-0013', assignedDoctor: 'Dr. Arjun Nair', assignedNurse: 'Joseph Thomas', ventilator: true, monitor: true, admittedAt: '2026-08-05', estimatedDischarge: '2026-08-14' },
  { id: 'b008', number: 'ICU-Bed-08', ward: 'ICU-2', type: 'ICU', status: 'Available', ventilator: false, monitor: true },
  { id: 'b009', number: 'GW-A-01', ward: 'General Ward A', type: 'General', status: 'Occupied', patientName: 'Arjun Singh', patientMrn: 'MEDSET-2026-0006', assignedDoctor: 'Dr. Meera Iyer', assignedNurse: 'Fatima Begum', admittedAt: '2026-08-03' },
  { id: 'b010', number: 'GW-A-02', ward: 'General Ward A', type: 'General', status: 'Available' },
  { id: 'b011', number: 'GW-A-03', ward: 'General Ward A', type: 'General', status: 'Cleaning' },
  { id: 'b012', number: 'GW-B-12', ward: 'General Ward B', type: 'General', status: 'Occupied', patientName: 'Priya Nair', patientMrn: 'MEDSET-2026-0002', assignedDoctor: 'Dr. Meera Iyer', assignedNurse: 'Anita Verma', admittedAt: '2026-08-05' },
  { id: 'b013', number: 'GW-B-13', ward: 'General Ward B', type: 'General', status: 'Available' },
  { id: 'b014', number: 'ER-01', ward: 'Emergency', type: 'Emergency', status: 'Occupied', patientName: 'Ananya Desai', patientMrn: 'MEDSET-2026-0004', assignedDoctor: 'Dr. Suresh Patel', admittedAt: '2026-08-06' },
  { id: 'b015', number: 'ER-02', ward: 'Emergency', type: 'Emergency', status: 'Available' },
  { id: 'b016', number: 'PV-01', ward: 'Private Ward', type: 'Private', status: 'Reserved' },
  { id: 'b017', number: 'PV-02', ward: 'Private Ward', type: 'Private', status: 'Available' },
  { id: 'b018', number: 'ISO-01', ward: 'Isolation', type: 'Isolation', status: 'Available' },
];

export const medicines: Medicine[] = [
  { id: 'm001', name: 'Aspirin 75mg', category: 'Antiplatelet', manufacturer: 'Sun Pharma', batchNumber: 'SP2026A75', stock: 2400, unit: 'tablets', reorderLevel: 500, expiryDate: '2027-06-30', price: 0.5, location: 'Rack A-1' },
  { id: 'm002', name: 'Atorvastatin 40mg', category: 'Statin', manufacturer: 'Cipla', batchNumber: 'CP2026AT40', stock: 1800, unit: 'tablets', reorderLevel: 400, expiryDate: '2027-03-15', price: 3.2, location: 'Rack A-2' },
  { id: 'm003', name: 'Metoprolol 25mg', category: 'Beta Blocker', manufacturer: 'Lupin', batchNumber: 'LP2026MT25', stock: 120, unit: 'tablets', reorderLevel: 300, expiryDate: '2026-09-30', price: 1.8, location: 'Rack B-1' },
  { id: 'm004', name: 'Ceftriaxone 1g', category: 'Antibiotic', manufacturer: 'Hetero', batchNumber: 'HT2026CF1G', stock: 850, unit: 'vials', reorderLevel: 200, expiryDate: '2027-01-20', price: 45, location: 'Cold Storage C-1' },
  { id: 'm005', name: 'Azithromycin 500mg', category: 'Antibiotic', manufacturer: 'Mankind', batchNumber: 'MK2026AZ500', stock: 60, unit: 'tablets', reorderLevel: 200, expiryDate: '2026-08-15', price: 12, location: 'Rack B-2' },
  { id: 'm006', name: 'Paracetamol 650mg', category: 'Analgesic', manufacturer: 'Micro Labs', batchNumber: 'ML2026PC650', stock: 5000, unit: 'tablets', reorderLevel: 1000, expiryDate: '2028-02-28', price: 1.2, location: 'Rack A-3' },
  { id: 'm007', name: 'Insulin Glargine', category: 'Insulin', manufacturer: 'Sanofi', batchNumber: 'SF2026IGL', stock: 340, unit: 'vials', reorderLevel: 100, expiryDate: '2027-05-10', price: 280, location: 'Cold Storage C-2' },
  { id: 'm008', name: 'Amlodipine 5mg', category: 'Calcium Channel Blocker', manufacturer: 'Cadila', batchNumber: 'CD2026AM5', stock: 2200, unit: 'tablets', reorderLevel: 500, expiryDate: '2027-08-20', price: 2.1, location: 'Rack A-4' },
  { id: 'm009', name: 'Ondansetron 4mg', category: 'Anti-emetic', manufacturer: 'Alembic', batchNumber: 'AL2026OD4', stock: 15, unit: 'tablets', reorderLevel: 150, expiryDate: '2026-10-05', price: 4.5, location: 'Rack B-3' },
  { id: 'm010', name: 'Metformin 500mg', category: 'Anti-diabetic', manufacturer: 'USV', batchNumber: 'USV2026MT500', stock: 3200, unit: 'tablets', reorderLevel: 600, expiryDate: '2027-12-15', price: 0.8, location: 'Rack A-5' },
];

export const labTests: LabTest[] = [
  { id: 'l001', orderId: 'LAB-2026-0101', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', testName: 'Troponin I (Quantitative)', category: 'Cardiac', orderedBy: 'Dr. Aarav Sharma', orderedAt: '2026-08-04T22:00:00', status: 'Verified', result: '4.2 ng/mL', normalRange: '< 0.04 ng/mL', priority: 'STAT', cost: 800 },
  { id: 'l002', orderId: 'LAB-2026-0102', patientName: 'Priya Nair', patientMrn: 'MEDSET-2026-0002', testName: 'Urine Culture & Sensitivity', category: 'Microbiology', orderedBy: 'Dr. Meera Iyer', orderedAt: '2026-08-05T10:00:00', status: 'Processing', priority: 'Urgent', cost: 350 },
  { id: 'l003', orderId: 'LAB-2026-0103', patientName: 'Mohammed Ali', patientMrn: 'MEDSET-2026-0003', testName: 'HbA1c', category: 'Diabetes', orderedBy: 'Dr. Vikram Reddy', orderedAt: '2026-08-06T08:00:00', status: 'Completed', result: '7.8%', normalRange: '< 5.7%', priority: 'Routine', cost: 450 },
  { id: 'l004', orderId: 'LAB-2026-0104', patientName: 'Ananya Desai', patientMrn: 'MEDSET-2026-0004', testName: 'CBC (Complete Blood Count)', category: 'Hematology', orderedBy: 'Dr. Suresh Patel', orderedAt: '2026-08-06T06:30:00', status: 'Sample Collected', priority: 'STAT', cost: 250 },
  { id: 'l005', orderId: 'LAB-2026-0105', patientName: 'Arjun Singh', patientMrn: 'MEDSET-2026-0006', testName: 'Sputum Culture', category: 'Microbiology', orderedBy: 'Dr. Meera Iyer', orderedAt: '2026-08-04T09:00:00', status: 'Processing', priority: 'Routine', cost: 400 },
  { id: 'l006', orderId: 'LAB-2026-0106', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', testName: 'Lipid Profile', category: 'Biochemistry', orderedBy: 'Dr. Aarav Sharma', orderedAt: '2026-08-05T07:00:00', status: 'Completed', result: 'Total Cholesterol 245 mg/dL, LDL 168 mg/dL, HDL 38 mg/dL', normalRange: 'TC < 200, LDL < 100, HDL > 40', priority: 'Routine', cost: 600 },
  { id: 'l007', orderId: 'LAB-2026-0107', patientName: 'Lakshmi Krishnan', patientMrn: 'MEDSET-2026-0005', testName: 'Thyroid Profile (T3, T4, TSH)', category: 'Biochemistry', orderedBy: 'Dr. Aarav Sharma', orderedAt: '2026-08-01T11:00:00', status: 'Verified', result: 'TSH 2.4 mIU/L', normalRange: '0.4 - 4.0 mIU/L', priority: 'Routine', cost: 500 },
];

export const radiologyScans: RadiologyScan[] = [
  { id: 'r001', requestId: 'RAD-2026-0051', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', scanType: 'Echocardiogram', bodyPart: 'Heart', orderedBy: 'Dr. Aarav Sharma', orderedAt: '2026-08-05T08:00:00', status: 'Reported', findings: 'LVEF 42%, mild LV dysfunction, regional wall motion abnormality in LAD territory', impression: 'Ischemic cardiomyopathy', radiologist: 'Dr. Neha Kapoor', cost: 2500 },
  { id: 'r002', requestId: 'RAD-2026-0052', patientName: 'Ananya Desai', patientMrn: 'MEDSET-2026-0004', scanType: 'Ultrasound', bodyPart: 'Abdomen', orderedBy: 'Dr. Suresh Patel', orderedAt: '2026-08-06T06:45:00', status: 'Completed', findings: 'Non-compressible tubular structure 11mm diameter in RIF, no free fluid', impression: 'Acute appendicitis', radiologist: 'Dr. Neha Kapoor', cost: 1200 },
  { id: 'r003', requestId: 'RAD-2026-0053', patientName: 'Arjun Singh', patientMrn: 'MEDSET-2026-0006', scanType: 'X-Ray', bodyPart: 'Chest', orderedBy: 'Dr. Meera Iyer', orderedAt: '2026-08-03T10:00:00', status: 'Verified', findings: 'Right lower lobe consolidation, no pleural effusion', impression: 'Right lower lobe pneumonia', radiologist: 'Dr. Neha Kapoor', cost: 400 },
  { id: 'r004', requestId: 'RAD-2026-0054', patientName: 'Mohammed Ali', patientMrn: 'MEDSET-2026-0003', scanType: 'MRI', bodyPart: 'Brain', orderedBy: 'Dr. Kavya Menon', orderedAt: '2026-08-06T09:30:00', status: 'Scheduled', cost: 6000 },
  { id: 'r005', requestId: 'RAD-2026-0055', patientName: 'Priya Nair', patientMrn: 'MEDSET-2026-0002', scanType: 'CT Scan', bodyPart: 'Abdomen/Pelvis', orderedBy: 'Dr. Meera Iyer', orderedAt: '2026-08-06T08:15:00', status: 'In Progress', cost: 3500 },
];

export const invoices: Invoice[] = [
  {
    id: 'inv001', invoiceNumber: 'INV-2026-0101', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', date: '2026-08-06', dueDate: '2026-08-13',
    items: [
      { description: 'ICU Bed (2 days)', quantity: 2, rate: 15000, amount: 30000, category: 'Room' },
      { description: 'Cardiology Consultation', quantity: 2, rate: 1500, amount: 3000, category: 'Consultation' },
      { description: 'Echocardiogram', quantity: 1, rate: 2500, amount: 2500, category: 'Radiology' },
      { description: 'Troponin I (STAT)', quantity: 1, rate: 800, amount: 800, category: 'Lab' },
      { description: 'Pharmacy - Aspirin, Atorvastatin, Metoprolol', quantity: 1, rate: 1200, amount: 1200, category: 'Pharmacy' },
    ],
    subtotal: 37500, tax: 6750, discount: 2000, total: 42250, paid: 20000, balance: 22250, status: 'Partial', insurance: true, insuranceProvider: 'Star Health',
  },
  {
    id: 'inv002', invoiceNumber: 'INV-2026-0102', patientName: 'Priya Nair', patientMrn: 'MEDSET-2026-0002', date: '2026-08-06', dueDate: '2026-08-13',
    items: [
      { description: 'General Ward (1 day)', quantity: 1, rate: 3000, amount: 3000, category: 'Room' },
      { description: 'Pulmonology Consultation', quantity: 1, rate: 1200, amount: 1200, category: 'Consultation' },
      { description: 'Urine Culture', quantity: 1, rate: 350, amount: 350, category: 'Lab' },
      { description: 'Ceftriaxone 1g IV', quantity: 2, rate: 45, amount: 90, category: 'Pharmacy' },
    ],
    subtotal: 4640, tax: 835, discount: 0, total: 5475, paid: 5475, balance: 0, status: 'Paid', insurance: true, insuranceProvider: 'HDFC Ergo',
  },
  {
    id: 'inv003', invoiceNumber: 'INV-2026-0103', patientName: 'Mohammed Ali', patientMrn: 'MEDSET-2026-0003', date: '2026-08-06', dueDate: '2026-08-20',
    items: [
      { description: 'Endocrinology Consultation', quantity: 1, rate: 1000, amount: 1000, category: 'Consultation' },
      { description: 'HbA1c', quantity: 1, rate: 450, amount: 450, category: 'Lab' },
    ],
    subtotal: 1450, tax: 261, discount: 0, total: 1711, paid: 0, balance: 1711, status: 'Unpaid', insurance: false,
  },
  {
    id: 'inv004', invoiceNumber: 'INV-2026-0104', patientName: 'Ananya Desai', patientMrn: 'MEDSET-2026-0004', date: '2026-08-06', dueDate: '2026-08-06',
    items: [
      { description: 'Emergency Room Charges', quantity: 1, rate: 2000, amount: 2000, category: 'Other' },
      { description: 'Surgery Consultation', quantity: 1, rate: 1500, amount: 1500, category: 'Consultation' },
      { description: 'Ultrasound Abdomen', quantity: 1, rate: 1200, amount: 1200, category: 'Radiology' },
      { description: 'CBC', quantity: 1, rate: 250, amount: 250, category: 'Lab' },
    ],
    subtotal: 4950, tax: 891, discount: 0, total: 5841, paid: 0, balance: 5841, status: 'Unpaid', insurance: false,
  },
  {
    id: 'inv005', invoiceNumber: 'INV-2026-0105', patientName: 'Lakshmi Krishnan', patientMrn: 'MEDSET-2026-0005', date: '2026-07-28', dueDate: '2026-08-04',
    items: [
      { description: 'General Ward (4 days)', quantity: 4, rate: 3000, amount: 12000, category: 'Room' },
      { description: 'Cardiology Consultation', quantity: 3, rate: 1500, amount: 4500, category: 'Consultation' },
      { description: 'Thyroid Profile', quantity: 1, rate: 500, amount: 500, category: 'Lab' },
      { description: 'Pharmacy', quantity: 1, rate: 800, amount: 800, category: 'Pharmacy' },
    ],
    subtotal: 17800, tax: 3204, discount: 1000, total: 20004, paid: 20004, balance: 0, status: 'Paid', insurance: true, insuranceProvider: 'Star Health',
  },
];

export const auditLogs: AuditLog[] = [
  { id: 'al001', user: 'Dr. Aarav Sharma', role: 'doctor', action: 'VIEW', resource: 'Patient Record MEDSET-2026-0001', timestamp: '2026-08-06T08:32:00', ip: '10.0.1.24', status: 'Success', details: 'Accessed ICU patient chart' },
  { id: 'al002', user: 'Reception Desk 1', role: 'receptionist', action: 'CREATE', resource: 'Appointment a003', timestamp: '2026-08-06T08:15:00', ip: '10.0.1.50', status: 'Success', details: 'Scheduled pediatric vaccination' },
  { id: 'al003', user: 'System', role: 'super_admin', action: 'AI_GENERATE', resource: 'SOAP Note #SN-0042', timestamp: '2026-08-06T08:28:00', ip: '127.0.0.1', status: 'Success', details: 'AI scribe generated SOAP note from 12 min recording' },
  { id: 'al004', user: 'Unknown', role: 'doctor', action: 'LOGIN', resource: 'Auth', timestamp: '2026-08-06T07:55:00', ip: '203.0.113.45', status: 'Failed', details: 'Invalid credentials, 3rd attempt' },
  { id: 'al005', user: 'Pharmacy Unit', role: 'pharmacist', action: 'DISPENSE', resource: 'Medicine Metoprolol 25mg', timestamp: '2026-08-06T08:10:00', ip: '10.0.2.30', status: 'Success', details: 'Dispensed 30 tablets to ICU-Bed-04' },
  { id: 'al006', user: 'Lab Tech 2', role: 'lab_technician', action: 'UPDATE', resource: 'Lab Test LAB-2026-0103', timestamp: '2026-08-06T08:05:00', ip: '10.0.3.15', status: 'Success', details: 'HbA1c result entered: 7.8%' },
  { id: 'al007', user: 'Dr. Suresh Patel', role: 'doctor', action: 'APPROVE', resource: 'Surgery Schedule', timestamp: '2026-08-06T06:50:00', ip: '10.0.1.30', status: 'Success', details: 'Approved emergency appendectomy' },
  { id: 'al008', user: 'Billing Staff 1', role: 'billing_staff', action: 'CREATE', resource: 'Invoice INV-2026-0104', timestamp: '2026-08-06T06:30:00', ip: '10.0.4.10', status: 'Success', details: 'Generated ER invoice for Ananya Desai' },
];

export const notifications: Notification[] = [
  { id: 'n001', title: 'ICU Alert', message: 'Patient Rajesh Kumar (ICU-Bed-04) SpO2 dropped to 94%', type: 'critical', timestamp: '2026-08-06T08:35:00', read: false, module: 'ICU' },
  { id: 'n002', title: 'Lab Result Ready', message: 'HbA1c result for Mohammed Ali is ready for review', type: 'info', timestamp: '2026-08-06T08:05:00', read: false, module: 'Laboratory' },
  { id: 'n003', title: 'Low Stock Alert', message: 'Azithromycin 500mg is below reorder level (60 units)', type: 'warning', timestamp: '2026-08-06T07:50:00', read: false, module: 'Pharmacy' },
  { id: 'n004', title: 'SOAP Note Generated', message: 'AI scribe completed SOAP note for 09:00 appointment', type: 'success', timestamp: '2026-08-06T08:28:00', read: true, module: 'AI Scribe' },
  { id: 'n005', title: 'Invoice Overdue', message: 'Invoice INV-2026-0103 is overdue by 0 days', type: 'warning', timestamp: '2026-08-06T06:00:00', read: true, module: 'Billing' },
  { id: 'n006', title: 'Bed Available', message: 'ICU-Bed-02 is now available after cleaning', type: 'info', timestamp: '2026-08-06T05:45:00', read: true, module: 'ICU' },
];

export const soapNotes: SoapNote[] = [
  {
    id: 'sn001', patientName: 'Rajesh Kumar', patientMrn: 'MEDSET-2026-0001', doctorName: 'Dr. Aarav Sharma', date: '2026-08-06',
    subjective: 'Patient is a 54-year-old male admitted with acute myocardial infarction. Reports mild chest discomfort since morning, denies shortness of breath. No new complaints. Tolerating oral intake well.',
    objective: 'BP 140/90, HR 92, SpO2 94% on 2L nasal cannula, Temp 99.2F, RR 20. Cardiovascular: Regular rate and rhythm, no murmurs. Lungs: Clear bilaterally. ECG: Sinus rhythm with Q waves in anterior leads. Echo: LVEF 42%.',
    assessment: 'Post-MI day 2. Patient is clinically stable on dual antiplatelet therapy, statin, and beta blocker. LVEF remains reduced at 42%. Current blood pressure is above target. Oxygen saturation has slightly decreased from 96% to 94%.',
    plan: '1. Continue current medications (Aspirin 75mg, Atorvastatin 40mg, Metoprolol 25mg). 2. Increase nasal cannula to 3L/min and monitor SpO2 q2h. 3. Add Amlodipine 5mg for BP control. 4. Repeat troponin in 6 hours. 5. Cardiology follow-up tomorrow. 6. Monitor for any signs of heart failure.',
    status: 'Approved',
    duration: 720,
    entities: [
      { text: 'acute myocardial infarction', type: 'Condition', confidence: 0.98, icdCode: 'I21.9' },
      { text: 'Aspirin 75mg', type: 'Medication', confidence: 0.97 },
      { text: 'Atorvastatin 40mg', type: 'Medication', confidence: 0.96 },
      { text: 'Metoprolol 25mg', type: 'Medication', confidence: 0.95 },
      { text: 'Amlodipine 5mg', type: 'Medication', confidence: 0.94 },
      { text: 'Penicillin', type: 'Allergy', confidence: 0.92 },
      { text: 'LVEF 42%', type: 'Symptom', confidence: 0.89 },
    ],
  },
  {
    id: 'sn002', patientName: 'Mohammed Ali', patientMrn: 'MEDSET-2026-0003', doctorName: 'Dr. Vikram Reddy', date: '2026-08-06',
    subjective: 'Patient is a 67-year-old male with known Type 2 Diabetes Mellitus presenting for routine follow-up. Reports good adherence to medications. Denies polyuria, polydipsia, or blurred vision. Occasional morning fasting sugars around 140 mg/dL.',
    objective: 'BP 128/82, HR 76, BMI 27.5. Foot exam: No neuropathy, no ulcers. HbA1c: 7.8% (improved from 8.4%). Fasting glucose: 142 mg/dL. Post-prandial: 198 mg/dL. Renal function: Normal.',
    assessment: 'Type 2 Diabetes Mellitus, moderately controlled. HbA1c improved but still above target (< 7%). Current regimen with Glimepiride and Pioglitazone is partially effective. No evidence of diabetic complications at this time.',
    plan: '1. Continue Glimepiride 2mg and Pioglitazone 15mg. 2. Add Metformin 500mg twice daily (note: previously reported Metformin intolerance — verify). 3. Dietary counseling referral. 4. Repeat HbA1c in 3 months. 5. Annual eye exam and microalbuminuria screening. 6. Follow-up in 4 weeks.',
    status: 'Reviewed',
    duration: 480,
    entities: [
      { text: 'Type 2 Diabetes Mellitus', type: 'Condition', confidence: 0.99, icdCode: 'E11.9' },
      { text: 'Glimepiride 2mg', type: 'Medication', confidence: 0.96 },
      { text: 'Pioglitazone 15mg', type: 'Medication', confidence: 0.95 },
      { text: 'Metformin 500mg', type: 'Medication', confidence: 0.93 },
      { text: 'Metformin', type: 'Allergy', confidence: 0.88 },
    ],
  },
];

export const dashboardStats = {
  totalPatients: 1248,
  admitted: 86,
  icuPatients: 12,
  emergencyCases: 4,
  appointmentsToday: 47,
  bedOccupancy: 78,
  icuOccupancy: 67,
  revenueToday: 284500,
  revenueMonth: 6420000,
  staffOnDuty: 34,
  pendingLabTests: 18,
  lowStockMeds: 3,
  aiNotesGenerated: 156,
  aiAccuracy: 94.2,
};

export const revenueData = [
  { month: 'Jan', revenue: 4200000, expenses: 2800000 },
  { month: 'Feb', revenue: 4500000, expenses: 2900000 },
  { month: 'Mar', revenue: 4800000, expenses: 3100000 },
  { month: 'Apr', revenue: 5100000, expenses: 3200000 },
  { month: 'May', revenue: 5600000, expenses: 3400000 },
  { month: 'Jun', revenue: 5900000, expenses: 3500000 },
  { month: 'Jul', revenue: 6200000, expenses: 3700000 },
  { month: 'Aug', revenue: 6420000, expenses: 3800000 },
];

export const patientFlowData = [
  { day: 'Mon', admissions: 12, discharges: 8, emergency: 5 },
  { day: 'Tue', admissions: 15, discharges: 10, emergency: 3 },
  { day: 'Wed', admissions: 10, discharges: 12, emergency: 7 },
  { day: 'Thu', admissions: 18, discharges: 9, emergency: 4 },
  { day: 'Fri', admissions: 20, discharges: 14, emergency: 8 },
  { day: 'Sat', admissions: 14, discharges: 11, emergency: 6 },
  { day: 'Sun', admissions: 8, discharges: 7, emergency: 3 },
];

export const departmentData = [
  { name: 'Cardiology', patients: 142, revenue: 1850000 },
  { name: 'Pulmonology', patients: 98, revenue: 920000 },
  { name: 'Neurology', patients: 76, revenue: 1240000 },
  { name: 'Orthopedics', patients: 134, revenue: 1100000 },
  { name: 'Pediatrics', patients: 210, revenue: 680000 },
  { name: 'Endocrinology', patients: 88, revenue: 540000 },
  { name: 'Nephrology', patients: 54, revenue: 990000 },
  { name: 'Surgery', patients: 67, revenue: 2100000 },
];

export const icuTrendData = [
  { time: '00:00', occupancy: 58, alerts: 2 },
  { time: '04:00', occupancy: 62, alerts: 1 },
  { time: '08:00', occupancy: 67, alerts: 3 },
  { time: '12:00', occupancy: 71, alerts: 2 },
  { time: '16:00', occupancy: 69, alerts: 4 },
  { time: '20:00', occupancy: 67, alerts: 1 },
];
