import type { ReactNode } from 'react';
import { ArrowUpRight, Search, type LucideIcon } from 'lucide-react';
import { Card, Input, Badge } from './ui';
export function PageHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{action}</div>; }
export function StatCard({ label, value, change, icon: Icon, tone='blue' }: { label: string; value: string|number; change?: string; icon: LucideIcon; tone?: 'blue'|'green'|'amber'|'red' }) { return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{change&&<p className="mt-1 text-xs text-emerald-600">{change}</p>}</div><div className={`rounded-lg p-2.5 ${tone==='green'?'bg-emerald-100 text-emerald-600':tone==='amber'?'bg-amber-100 text-amber-600':tone==='red'?'bg-red-100 text-red-600':'bg-sky-100 text-sky-600'}`}><Icon className="h-5 w-5"/></div></div></Card>; }
export function SearchBar({ value, onChange, placeholder='Search...' }: { value: string; onChange: (value:string)=>void; placeholder?: string }) { return <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="pl-9"/></div>; }
export function StatusBadge({ status }: { status: string }) { const lower=status.toLowerCase(); const tone=lower.includes('completed')||lower.includes('paid')||lower.includes('available')||lower.includes('success')||lower.includes('active')||lower.includes('confirmed')?'success':lower.includes('critical')||lower.includes('cancel')||lower.includes('failed')||lower.includes('maintenance')?'danger':lower.includes('pending')||lower.includes('partial')||lower.includes('progress')||lower.includes('warning')||lower.includes('occupied')?'warning':'info'; return <Badge tone={tone}>{status}</Badge>; }
export function EmptyState({ title='No results found', description='Try adjusting your search or filters.' }: { title?: string; description?: string }) { return <div className="rounded-xl border border-dashed p-12 text-center"><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>; }
export function SectionLink({ children }: { children: ReactNode }) { return <span className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">{children}<ArrowUpRight className="h-3.5 w-3.5"/></span>; }
