'use client';
import * as React from 'react';
import { cn } from '@/lib/utils';
export function Button({ className, variant='default', size='default', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'default'|'outline'|'ghost'|'destructive'|'success'; size?: 'default'|'sm'|'lg' }) { return <button className={cn('inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50', variant==='default'&&'bg-primary text-primary-foreground hover:bg-primary/90', variant==='outline'&&'border bg-background hover:bg-muted', variant==='ghost'&&'hover:bg-muted', variant==='destructive'&&'bg-destructive text-destructive-foreground hover:bg-destructive/90', variant==='success'&&'bg-success text-success-foreground hover:bg-success/90', size==='default'&&'h-10 px-4 text-sm', size==='sm'&&'h-8 px-3 text-xs', size==='lg'&&'h-11 px-6', className)} {...props}/>; }
export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn('rounded-xl border bg-card text-card-foreground shadow-sm', className)} {...props}/>; }
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn('flex h-10 w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring', className)} {...props}/>; }
export function Textarea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn('flex min-h-24 w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring', className)} {...props}/>; }
export function Label({ className, ...props }: React.LabelHTMLAttributes<HTMLLabelElement>) { return <label className={cn('text-sm font-medium leading-none', className)} {...props}/>; }
export function Select({ className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn('flex h-10 w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring', className)} {...props}/>; }
export function Badge({ className, tone='neutral', ...props }: React.HTMLAttributes<HTMLSpanElement> & { tone?: 'neutral'|'success'|'warning'|'danger'|'info' }) { return <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium', tone==='neutral'&&'bg-muted text-muted-foreground', tone==='success'&&'bg-emerald-100 text-emerald-700', tone==='warning'&&'bg-amber-100 text-amber-700', tone==='danger'&&'bg-red-100 text-red-700', tone==='info'&&'bg-sky-100 text-sky-700', className)} {...props}/>; }
export function Dialog({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: React.ReactNode }) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={onClose}><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-card p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><Button variant="ghost" size="sm" onClick={onClose}>Close</Button></div>{children}</div></div>; }
